;-----------------------------------------------------------------
; TD Nø1 module CONST.INC           
; Constantes utilisees dans le noyau   (version de TESTFILE)
;-----------------------------------------------------------------
; Types associes aux descriteurs
TypeFPrio   	equ   	'Q'	; File prioritaire
TypeFDP		equ	'F'	; file des procs
TypeCellule	equ	'c'	; cellule quelconque (desscripteur)

; Identites des cellules/files
Id1	 	equ	'1'
Id2	 	equ	'2'
Id3	 	equ	'3'

IdCGQueueExp	EQU 	'Q'	; cellule de garde de la queue d'exp
IdCGFileDesProc	EQU 	'F'	; cellule de garde de la file des procs
